// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Testingcreationofnewcustomer() 
  {
    // Test name: testing - creation of new customer
    // Step # | name | target | value
    // 1 | open | / | 
    // Abrindo o web app
    driver.Navigate().GoToUrl("https://dev-env1221.azurewebsites.net/");
    // 2 | setWindowSize | 1382x744 | 
    // Expande tamanho do browser window
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    // 3 | click | css=.esh-catalog-item:nth-child(1) .esh-catalog-button | 
    // click - produto
    driver.FindElement(By.CssSelector(".esh-catalog-item:nth-child(1) .esh-catalog-button")).Click();
    // 4 | click | css=.btn:nth-child(2) | 
    // click - checkout
    driver.FindElement(By.CssSelector(".btn:nth-child(2)")).Click();
    // 5 | click | linkText=Register as a new user | 
    // click - Register as a new user
    driver.FindElement(By.LinkText("Register as a new user")).Click();
    // 6 | click | id=Input_Email | 
    // click - Email
    driver.FindElement(By.Id("Input_Email")).Click();
    // 7 | type | id=Input_Email | wesleygomespaiva43@hotmail.com
    // Digita e-mail
    driver.FindElement(By.Id("Input_Email")).SendKeys("wesleygomespaiva43@hotmail.com");
    // 8 | type | id=Input_Password | 12345678
    // Digita senha
    driver.FindElement(By.Id("Input_Password")).SendKeys("12345678");
    // 9 | type | id=Input_ConfirmPassword | 12345678
    // Confirma senha
    driver.FindElement(By.Id("Input_ConfirmPassword")).SendKeys("12345678");
    // 10 | click | css=.btn | 
    // click - Register
    driver.FindElement(By.CssSelector(".btn")).Click();
  }

  [Fact]
  public void MyTestCleanup()
  {
     driver.Quit();
  }
}
